### PR TITLE
adding default timeout and optional timeout per method call

### PR DESCRIPTION
**Pull request by guilhebl**
Adding optional timeouts per request and a global default timeout

### CODE REVIEW

**Comment by mattbit** [comment]
Hi @guilhebl, thanks for raising this issue. I opened #7, which allows to set the HTTP client used by the library. This should also solve your problem, right?
In my opinion this may be a more flexible solution and also offers some perks (e.g. using the Google Appengine HTTP client).

@cybercase what do you think?

**Comment by cybercase** [comment]
@mattbit Nice and clean. 👍  for me. I was thinking about adding a new test for this feature, but maybe it's not essential.

**Comment by guilhebl** [comment]
hi @mattbit , yes it does solve the timeout scenarios. I'll close my PR in this case.

**Comment by mattbit** [comment]
Great!

**Pull request closed without merging**
